"""
ARC Attribution Module

The attribution layer estimates:

    P(L_i | E_t)

where:

    L_i = structural layer potentially responsible for failure
    E_t = environmental evidence generated by reality coupling

This module converts raw failure evidence into causal localization
signals used by the ARC governor.

Pipeline position:

    Γ → E_t → Attribution → FA_c → λ_A → Π_A → ΔS
"""

from .diagnosis import (
    FailureLayer,
    FailurePosterior,
    AttributionEngine,
)

from .confidence import (
    attribution_confidence,
)

__all__ = [
    "FailureLayer",
    "FailurePosterior",
    "AttributionEngine",
    "attribution_confidence",
]
